### ISSUE TITLE
error when running run_rw.py

### ISSUE THREAD

**Issue by zxhero** [facebookresearch/griphin#3]
Hi, 
I compiled and ran random work as wroten in README:
` python3 engine/setup.py build_ext --build-lib=frontend`
` python3 frontend/run_rw.py --data_path ./data --num_roots 8192 --walk_length 15 --num_machines 4 --dataset ogbn-arxiv`
There is no error reported compiling it: 
![image](https://github.com/facebookresearch/griphin/assets/21699586/ef37c648-2ddb-4e46-932e-326eec2ca273)
but I got the following error running run_rw.py:
`Traceback (most recent call last): `
  `File "/home/zhangxu/applications/griphin/frontend/run_rw.py", line 17, in <module>`
    `from graph import GraphDataManager`
  `File "/home/zhangxu/applications/griphin/frontend/graph.py", line 11, in <module>`
    `import graph_engine`
`ImportError: /home/zhangxu/applications/griphin/frontend/graph_engine.cpython-310-x86_64-linux-gnu.so: undefined symbol: GOMP_loop_maybe_nonmonotonic_runtime_next`
I tried to add `-lgomp` into `setup.py` but the error remains.
I used g++ 11 and mpich on ubuntu 22.04
Could someone help me out? Thanks~

**Comment by Hydrapse** [comment]
I'm sorry for the late reply. It seems that there's a compatibility issue with your `gcc` and `libgomp1`. I suggest reinstalling them to solve this issue.
